service: servico-pagamento-fast-food

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  environment:
    DATABASE_URL: postgresql://bd_pagamento:TsTxHm123daseq@bd-pagamento-servico.cjiacqmy6qd1.us-east-1.rds.amazonaws.com:5432/bd_pagamento
    URL_PEDIDO: # Adicione a URL do pedido, se necessário
    URL_PAGAMENTO: # Adicione a URL do pagamento, se necessário
  vpc:
    securityGroupIds:
      - ${self:custom.dbConfig.securityGroup}
    subnetIds:
      - subnet-06b2de7dc8b0e52d6
      - subnet-072932e7d1f8a8e87
      - subnet-05e02de9c0092df5b
      - subnet-0093cd8eb65689bef
      - subnet-0bff80e356ded0471
      - subnet-0c0a94217709865b8

functions:
  app:
    handler: dist/handler.handler
    environment:
      DATABASE_URL: postgres://postgres:pagamentos@bd-pagamento-servico.cjiacqmy6qd1.us-east-1.rds.amazonaws.com:5432/bd-pagamentos
      URL_PEDIDO: teste
      URL_PAGAMENTO: teste
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-${self:provider.stage}-api

    ApiGatewayDeployment:
      Type: AWS::ApiGateway::Deployment
      DependsOn:
        - ApiGatewayRestApi
      Properties:
        RestApiId:
          Ref: ApiGatewayRestApi

    ApiGatewayStage:
      Type: AWS::ApiGateway::Stage
      DependsOn:
        - ApiGatewayDeployment
      Properties:
        DeploymentId:
          Ref: ApiGatewayDeployment
        RestApiId:
          Ref: ApiGatewayRestApi
        StageName: ${self:provider.stage}

    ApiGatewayMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        RestApiId:
          Ref: ApiGatewayRestApi
        ResourceId:
          Fn::GetAtt: [ApiGatewayRestApi, RootResourceId]
        HttpMethod: GET
        AuthorizationType: NONE
        Integration:
          IntegrationHttpMethod: POST
          Type: AWS_PROXY
          Uri: 
            Fn::Sub: arn:aws:apigateway:${self:provider.region}:lambda:path/2015-03-31/functions/${self:service}-${self:provider.stage}-app:${self:provider.stage}/invocations

    MyDBInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        DBInstanceIdentifier: bd-pagamento-servico
        DBInstanceClass: db.t3.micro
        Engine: postgres
        EngineVersion: "13.15"
        MasterUsername: bd_pagamento
        MasterUserPassword: TsTxHm123daseq
        DBName: bd_pagamento
        AllocatedStorage: 20
        PubliclyAccessible: true  # Garante que o RDS seja publicamente acessível
        VPCSecurityGroups:
          - ${self:custom.dbConfig.securityGroup}

    MyDBSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security group for RDS access
        VpcId: vpc-032659b549a29f127  # Substitua pelo ID da sua VPC
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 5432
            ToPort: 5432
            CidrIp: 0.0.0.0/0  # Permitindo acesso público; use com cautela

    MyDBSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: "Subnet group for RDS instance"
        SubnetIds:
          - subnet-06b2de7dc8b0e52d6
          - subnet-072932e7d1f8a8e87
          - subnet-05e02de9c0092df5b
          - subnet-0093cd8eb65689bef
          - subnet-0bff80e356ded0471
          - subnet-0c0a94217709865b8

custom:
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true
  dbConfig:
    host: bd-pagamento-servico.cjiacqmy6qd1.us-east-1.rds.amazonaws.com
    port: 5432
    username: bd_pagamento
    password: TsTxHm123daseq
    dbName: bd_pagamento
    securityGroup: sg-0062601e5c0f0680d
    vpcId: vpc-032659b549a29f127
    subnets:
      - subnet-06b2de7dc8b0e52d6
      - subnet-072932e7d1f8a8e87
      - subnet-05e02de9c0092df5b
      - subnet-0093cd8eb65689bef
      - subnet-0bff80e356ded0471
      - subnet-0c0a94217709865b8