apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamento-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagamentos-fast-food
  template:
    metadata:
      labels:
        app: pagamentos-fast-food
    spec:
      containers:
        - name: pagamentos-fast-food
          image: public.ecr.aws/o9d4t2y8/pagamentos-fast-food:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@host.docker.internal:5432/bd-pagamento
            - name: URL_PEDIDOS
              value: http://pedidos-fast-food-service:3000/pedidos
            
---
apiVersion: v1
kind: Service
metadata:
  name: pagamentos-fast-food-service
spec:
  selector:
    app: pagamentos-fast-food
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
  